#ifndef __CLIENT_ERRORCODES_H__
#define __CLIENT_ERRORCODES_H__

// Error Codes
#define CMD_ERROR_SUCCESS 100
#define CMD_ERROR_INVALID_COMMAND 101
#define CMD_ERROR_INVALID_ARGUMENTS 102
#define CMD_ERROR_INVALID_ARGUMENTS_COUNT 103
#define CMD_ERROR_INVALID_ARGUMENTS_TYPE 104
#define CMD_ERROR_SEND_FAILED 105
#define CMD_ERROR_RECV_FAILED 106
#define CMD_ERROR_INVALID_RECV_VALUE 107
#define CMD_ERROR_SOCKET_FAILED 109
#define CMD_ERROR_CONNECT_FAILED 110

#endif // __CLIENT_ERRORCODES_H__