#ifndef __STORAGE_SERVER_ERROR_CODES_H__
#define __STORAGE_SERVER_ERROR_CODES_H__

#define ERROR_CODE_SUCCESS 300
#define ERROR_INVALID_OPERATION 301
#define ERROR_INVALID_AUTHENTICATION 302
#define ERROR_INVALID_PATH 303
#define ERROR_INVALID_ACCESS 304
#define ERROR_INVALID_FLAG 305

#endif // __STORAGE_SERVER_ERROR_CODES_H__